services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:5432"

volumes:
  psql_data: